TITLE: 'repr_table6_you2me_kinect_model'
DEBUG: false
DEBUG_FREQ: 5
LOGDIR: '/cluster/scratch/qimaqi/kinect_output'
DEVICE: 'cuda'
EXP_NAME: 'tcmr'
OUTPUT_DIR: 'experiments'
NUM_WORKERS: 16
SEED_VALUE: 1
DATASET:
  SEQLEN: 16
LOSS:
  KP_2D_W: 300.0
  KP_3D_W: 300.0
  SHAPE_W: 0.06
  POSE_W: 60.0
  D_MOTION_LOSS_W: 0.0
TRAIN:
  BATCH_SIZE: 32
  NUM_ITERS_PER_EPOCH: 500
  PRETRAINED: '/cluster/scratch/qimaqi/pretrained_model/tcmr_table6_mpii3d_test.pth.tar'
  PRETRAINED_REGRESSOR: '/cluster/home/qimaqi/VH/TCMR_RELEASE/data/base_data/spin_model_checkpoint.pth.tar'
  EVAL_WEIGHT: '/cluster/home/qimaqi/VH/TCMR_RELEASE/experiments/20-05-2022_16-59-49_tcmr/model_best.pth.tar' #'/cluster/home/qimaqi/VH/TCMR_RELEASE/experiments/25-04-2022_11-58-12_tcmr/checkpoint.pth.tar'
  RESUME: ''
  START_EPOCH: 0
  END_EPOCH: 32
  LR_PATIENCE: 5
  DATA_2D_RATIO: 0.6
  OVERLAP: false
  DATASETS_2D: []
  DATASETS_3D:
    - 'YOU2ME'
  DATASET_EVAL: 'YOU2ME'
  GEN_LR: 0.00005
  GEN_WD: 0.0
  MOT_DISCR:
    OPTIM: 'Adam'
    LR: 0.0001
    WD: 0.0001
    MOMENTUM: 0.9
    HIDDEN_SIZE: 1024
    NUM_LAYERS: 2
    FEATURE_POOL: 'attention'
    ATT:
      LAYERS: 3
      SIZE: 1024
      DROPOUT: 0.2
MODEL:
  TEMPORAL_TYPE: 'gru'
  TGRU:
    NUM_LAYERS: 2
    HIDDEN_SIZE: 1024